site_name: "Broad Institute Long Read Pipelines"
repo_url: "https://github.com/broadinstitute/long-read-pipelines"

site_description: "This repository contains pipelines for processing of long read data from PacBio and/or Oxford Nanopore platforms."
site_author: "Broad Institute"
copyright: "Copyright (c) 2019, Broad Institute"

theme: readthedocs

markdown_extensions:
    - def_list

