name: lr-metrics
channels:
  - defaults
  - conda-forge
  - bioconda
  - r
dependencies:
  - samtools
  - bedtools
  - java-jdk
  - r
  - r-devtools
  - r-shiny
  - r-tidyverse
  - r-viridis
  - r-hexbin
  - r-data.table
