name: lr-sv
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - atomicwrites=1.4.0=py_0
  - attrs=20.2.0=py_0
  - backports=1.0=py_2
  - bcftools=1.11=h7c999a4_0
  - bedtools=2.29.2=hc088bd4_0
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2021.4.13=h06a4308_1
  - certifi=2020.6.20=pyhd3eb1b0_3
  - configparser=4.0.2=py27_0
  - contextlib2=0.6.0.post1=py_0
  - cython=0.29.14=py27he6710b0_0
  - funcsigs=1.0.2=py27_0
  - gsl=2.6=h294904e_0
  - htslib=1.11=hd3b49d5_0
  - importlib_metadata=1.3.0=py27_0
  - intervaltree=3.1.0=py_0
  - java-jdk=8.0.112=1
  - k8=0.2.5=he513fc3_0
  - krb5=1.18.2=h173b8e3_0
  - libblas=3.8.0=17_openblas
  - libcblas=3.8.0=17_openblas
  - libcurl=7.71.1=h20c2e04_1
  - libdeflate=1.6=h516909a_0
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libopenblas=0.3.10=h5a2b251_0
  - libssh2=1.9.0=h1ba5d50_1
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - minimap2=2.17=hed695b0_3
  - more-itertools=5.0.0=py27_0
  - ncrf=1.00.06=py27h470a237_0
  - ncurses=6.2=he6710b0_1
  - openjdk=8.0.112=zulu8.19.0.1_3
  - openssl=1.1.1k=h27cfd23_0
  - packaging=20.4=py_0
  - pathlib2=2.3.5=py27_0
  - pbsv=2.6.0=h9ee0642_0
  - perl=5.26.2=h14c3975_0
  - pip=19.3.1=py27_0
  - pluggy=0.13.1=py27_0
  - progressbar2=3.37.1=py27_0
  - py=1.9.0=py_0
  - pyfaidx=0.5.9.1=pyh864c0ab_1
  - pyparsing=2.4.7=py_0
  - pytest=4.6.2=py27_0
  - pytest-runner=5.2=py_0
  - python=2.7.18=h15b4118_1
  - python-levenshtein=0.12.0=py27h7b6447c_1001
  - python-utils=2.3.0=py27_0
  - pyvcf=0.6.8=py27_1000
  - readline=8.0=h7b6447c_0
  - samtools=1.11=h6270b1f_0
  - scandir=1.10.0=py27h7b6447c_0
  - setuptools=44.0.0=py27_0
  - six=1.15.0=py_0
  - sniffles=1.0.12=h8b12597_1
  - sortedcontainers=2.2.2=py_0
  - sqlite=3.33.0=h62c20be_0
  - tclap=1.2.2=he1b5a44_0
  - tk=8.6.10=hbc83047_0
  - truvari=0.1.2018.08.10=1
  - wcwidth=0.2.5=py_0
  - wheel=0.35.1=py_0
  - xz=5.2.5=h7b6447c_0
  - zipp=0.6.0=py_0
  - zlib=1.2.11=h7b6447c_3
prefix: /opt/conda/envs/lr-sv
