name: lr-tama
channels:
  - bioconda
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - biopython=1.74=py27h7b6447c_0
  - blas=1.0=mkl
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2020.7.22=0
  - certifi=2019.11.28=py27_0
  - curl=7.71.1=hbc83047_1
  - intel-openmp=2020.2=254
  - krb5=1.18.2=h173b8e3_0
  - libcurl=7.71.1=h20c2e04_1
  - libdeflate=1.0=h14c3975_1
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libssh2=1.9.0=h1ba5d50_1
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - mkl=2019.4=243
  - mkl-service=2.3.0=py27he904b0f_0
  - mkl_fft=1.0.15=py27ha843d7b_0
  - mkl_random=1.1.0=py27hd6b4f25_0
  - ncurses=6.2=he6710b0_1
  - numpy=1.16.6=py27hbc911f0_0
  - numpy-base=1.16.6=py27hde5b4d6_0
  - openssl=1.1.1h=h7b6447c_0
  - pip=19.3.1=py27_0
  - pysam=0.15.3=py27hda2845c_1
  - python=2.7.18=h15b4118_1
  - readline=8.0=h7b6447c_0
  - setuptools=44.0.0=py27_0
  - six=1.15.0=py_0
  - sqlite=3.33.0=h62c20be_0
  - tk=8.6.10=hbc83047_0
  - wheel=0.35.1=py_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
