name: lr-gnomix
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - samtools
  - python==3.8
  - pip:
    - matplotlib==3.3.4
    - numpy==1.20.3
    - pandas==1.3.5
    - PyYAML==5.1.2
    - scikit-allel==1.3.1
    - scikit-learn==1.0.1
    - scipy==1.5.3
    - seaborn==0.11.2
    - sklearn-crfsuite==0.3.6
    - tqdm==4.62.3
    - uncertainty-calibration==0.0.7
    - xgboost==1.1.1
