name: lr-pb
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - aiohttp=3.6.3=py38h7b6447c_0
  - async-timeout=3.0.1=py38_0
  - attrs=20.2.0=py_0
  - brotlipy=0.7.0=py38h7b6447c_1000
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2020.7.22=0
  - cachetools=4.1.1=py_0
  - certifi=2020.6.20=py38_0
  - cffi=1.14.3=py38he30daa8_0
  - chardet=3.0.4=py38_1003
  - construct=2.9.45=py_0
  - cryptography=3.1.1=py38h1ba5d50_0
  - google-api-core=1.22.2=py38_0
  - google-auth=1.22.1=py_0
  - google-cloud-core=1.3.0=py_0
  - google-cloud-storage=1.28.1=py_0
  - google-resumable-media=0.5.1=py_0
  - googleapis-common-protos=1.52.0=py38_0
  - htslib=1.10.2=hd3b49d5_1
  - idna=2.10=py_0
  - isoseq3=3.4.0=0
  - java-jdk=8.0.112=1
  - krb5=1.18.2=h173b8e3_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libcurl=7.71.1=h20c2e04_1
  - libdeflate=1.6=h516909a_0
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libprotobuf=3.13.0.1=hd408876_0
  - libssh2=1.9.0=h1ba5d50_1
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - lima=2.0.0=0
  - multidict=4.7.6=py38h7b6447c_1
  - ncurses=6.2=he6710b0_1
  - openjdk=8.0.112=zulu8.19.0.1_3
  - openssl=1.1.1h=h7b6447c_0
  - pbbam=1.6.0=h5b7e6e0_0
  - pbccs=5.0.0=0
  - pbmm2=1.4.0=h56fc30b_0
  - pip=20.2.3=py38_0
  - protobuf=3.13.0=py38he6710b0_1
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.20=py_2
  - pyopenssl=19.1.0=py_1
  - pysam=0.16.0.1=py38hbdc2ae9_1
  - pysocks=1.7.1=py38_0
  - python=3.8.5=h7579374_1
  - python_abi=3.8=1_cp38
  - pytz=2020.1=py_0
  - readline=8.0=h7b6447c_0
  - requests=2.24.0=py_0
  - rsa=4.6=py_0
  - samtools=1.10=h2e538c0_3
  - setuptools=50.3.0=py38hb0f4dca_1
  - six=1.15.0=py_0
  - sqlite=3.33.0=h62c20be_0
  - tk=8.6.10=hbc83047_0
  - urllib3=1.25.10=py_0
  - wheel=0.35.1=py_0
  - xz=5.2.5=h7b6447c_0
  - yarl=1.6.0=py38h7b6447c_0
  - zlib=1.2.11=h7b6447c_3

