name: lr-cloud-downloader
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2022.12.7=ha878542_0
  - curl=7.86.0=hdc1c0ab_2
  - entrez-direct=16.2=he881be0_0
  - hdf5=1.12.1=nompi_h4df4325_104
  - icu=70.1=h27087fc_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.20.1=h81ceb04_0
  - ld_impl_linux-64=2.39=hcc3a1bd_1
  - libcurl=7.86.0=hdc1c0ab_2
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.2.0=h65d4601_19
  - libgfortran-ng=12.2.0=h69a702a_19
  - libgfortran5=12.2.0=h337968e_19
  - libgomp=12.2.0=h65d4601_19
  - libiconv=1.16=h516909a_0
  - libnghttp2=1.47.0=hff17c54_1
  - libnsl=2.0.0=h7f98852_0
  - libsqlite=3.40.0=h753d276_0
  - libssh2=1.10.0=hf14f497_3
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libuuid=2.32.1=h7f98852_1000
  - libxml2=2.9.14=h22db469_4
  - libzlib=1.2.13=h166bdaf_4
  - ncbi-ngs-sdk=3.0.1=pl5321h629fbf0_0
  - ncurses=6.3=h27087fc_1
  - openssl=3.0.7=h0b41bf4_1
  - ossuuid=1.6.2=hf484d3e_1000
  - parallel-fastq-dump=0.6.7=pyhdfd78af_0
  - perl=5.32.1=2_h7f98852_perl5
  - perl-alien-build=2.48=pl5321hec16e2b_0
  - perl-alien-libxml2=0.17=pl5321hec16e2b_0
  - perl-business-isbn=3.007=pl5321hd8ed1ab_0
  - perl-business-isbn-data=20210112.006=pl5321hd8ed1ab_0
  - perl-capture-tiny=0.48=pl5321ha770c72_1
  - perl-carp=1.50=pl5321hd8ed1ab_0
  - perl-constant=1.33=pl5321hd8ed1ab_0
  - perl-data-dumper=2.183=pl5321h166bdaf_0
  - perl-encode=3.19=pl5321h166bdaf_0
  - perl-exporter=5.74=pl5321hd8ed1ab_0
  - perl-extutils-makemaker=7.64=pl5321hd8ed1ab_0
  - perl-ffi-checklib=0.28=pl5321hdfd78af_0
  - perl-file-chdir=0.1011=pl5321hd8ed1ab_0
  - perl-file-path=2.18=pl5321hd8ed1ab_0
  - perl-file-temp=0.2304=pl5321hd8ed1ab_0
  - perl-file-which=1.24=pl5321hd8ed1ab_0
  - perl-importer=0.026=pl5321hd8ed1ab_0
  - perl-mime-base64=3.16=pl5321h166bdaf_0
  - perl-parent=0.239=pl5321hd8ed1ab_0
  - perl-path-tiny=0.124=pl5321hd8ed1ab_0
  - perl-pathtools=3.75=pl5321h166bdaf_0
  - perl-scope-guard=0.21=pl5321hd8ed1ab_0
  - perl-storable=3.15=pl5321h166bdaf_0
  - perl-sub-info=0.002=pl5321hd8ed1ab_0
  - perl-term-table=0.016=pl5321hdfd78af_0
  - perl-test2-suite=0.000145=pl5321hdfd78af_0
  - perl-uri=5.12=pl5321hdfd78af_0
  - perl-xml-libxml=2.0207=pl5321h661654b_0
  - perl-xml-namespacesupport=1.12=pl5321hd8ed1ab_0
  - perl-xml-sax=1.02=pl5321hd8ed1ab_0
  - perl-xml-sax-base=1.09=pl5321hd8ed1ab_0
  - pip=22.3.1=pyhd8ed1ab_0
  - python=3.11.0=ha86cf86_0_cpython
  - readline=8.1.2=h0f457ee_0
  - setuptools=65.5.1=pyhd8ed1ab_0
  - sra-tools=3.0.0=pl5321hd0d85c6_1
  - tk=8.6.12=h27826a3_0
  - tzdata=2022g=h191b570_0
  - wheel=0.38.4=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - zlib=1.2.13=h166bdaf_4
  - pip:
    - crcmod==1.7
prefix: /opt/conda/envs/lr-cloud-downloader
